version: "3.8"

services: 
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-volumne:/data/db
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: komalsingh54/api:latest
    container_name: api
    restart: always
    environment: 
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=animal
    depends_on: 
      - mongodb
    ports:
      - "3000:3000"