# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb
  labels:
    name:  mongodb
spec:
  selector:
    matchLabels:
      service: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        service:  mongodb
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  mongodb
        image:  mongo
      restartPolicy: Always
---
